- hosts: 192.168.43.63
  tasks:
    - name: create yum repository for docker
      yum_repository:
        name: docker
        description: this is docker repo ceated by ansible
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
    - name: install docker
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present
    - name: start my docker services
      service:
        name: "docker"
        state: started
    - name: Create a directory for mount
      file:
        path: /task1_ansible
        state: directory
        mode: '0755'
    - name: copy file into the created directory
      copy:
        src: "home.html"
        dest: "/task1_ansible/"
    - pip:
         name: docker-py
    - name: creting an docker container
      docker_container:
        name: webos
        image: httpd:latest
        ports:
                - "1234:80"
        volumes:
                - /task1_ansible:/usr/local/apache2/htdocs/
